SET ECHO ON;

CREATE TABLE COMPANIAS (
    Codigo VARCHAR(10) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE MODELO (
    Modelo VARCHAR(30) PRIMARY KEY,
    Fabricante VARCHAR(30) NOT NULL,
    Motor VARCHAR(20) 
);

CREATE TABLE AEROPUERTOS (
    IATA VARCHAR(5) PRIMARY KEY,
    Nombre VARCHAR(50),
    Ciudad VARCHAR(30),
    Estado VARCHAR(30)
);

CREATE TABLE AVIONES (
    Matricula VARCHAR(10) PRIMARY KEY,
    Compania VARCHAR(10),
    Modelo VARCHAR(30),
    AgnoFabricacion NUMBER(4),
    FOREIGN KEY(Modelo) REFERENCES MODELO(Modelo) ON DELETE CASCADE,
    FOREIGN KEY(Compania) REFERENCES COMPANIAS(Codigo) ON DELETE CASCADE
);

CREATE TABLE VUELOS (
    IdVuelo NUMBER(6) PRIMARY KEY,
    Numero NUMBER(6),
    Avion VARCHAR(10),
    AeropuertoO VARCHAR(5),
    AeropuertoD VARCHAR(5),
    FechSalida DATE,
    FechLlegada DATE,
    FOREIGN KEY(Avion) REFERENCES AVIONES(Matricula) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoO) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoD) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE
);


CREATE TABLE DESVIOS (
    IdDesvio NUMBER(6) PRIMARY KEY,
    Vuelo NUMBER(6),
    AeropuertoAlt VARCHAR(5),
    FOREIGN KEY(Vuelo) REFERENCES VUELOS(IdVuelo) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoAlt) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE
);

CREATE TABLE RETRASOS (
    IdRetraso NUMBER(6) PRIMARY KEY,
    Vuelo NUMBER(6),
    Causa VARCHAR(50),
    Duracion NUMBER(4),
    FOREIGN KEY(Vuelo) REFERENCES VUELOS(IdVuelo) ON DELETE CASCADE
);




CREATE TABLE CANCELACIONES (
    IdCancelacion NUMBER(6) PRIMARY KEY,
    Vuelo NUMBER(6),
    FOREIGN KEY(Vuelo) REFERENCES VUELOS(IdVuelo) ON DELETE CASCADE
);



