SET ECHO ON;

CREATE TABLE COMPANIAS (
    Codigo VARCHAR(10) PRIMARY KEY,
    Nombre VARCHAR(100) NOT NULL
);

CREATE TABLE MODELO (
    Modelo VARCHAR(30) PRIMARY KEY,
    Fabricante VARCHAR(30) NOT NULL,
    Motor VARCHAR(20) 
);

CREATE TABLE AEROPUERTOS (
    IATA VARCHAR(5) PRIMARY KEY,
    Nombre VARCHAR(50),
    Ciudad VARCHAR(30),
    Estado VARCHAR(30)
);

CREATE TABLE AVIONES (
    Matricula VARCHAR(10) PRIMARY KEY,
    Compania VARCHAR(10),
    Modelo VARCHAR(30),
    AgnoFabricacion NUMBER(4),
    FOREIGN KEY(Modelo) REFERENCES MODELO(Modelo) ON DELETE CASCADE,
    FOREIGN KEY(Compania) REFERENCES COMPANIAS(Codigo) ON DELETE CASCADE
);

CREATE TABLE VUELOS (
    IdVuelo NUMBER(6) PRIMARY KEY,
    Numero NUMBER(6),
    Avion VARCHAR(10),
    AeropuertoO VARCHAR(5),
    AeropuertoD VARCHAR(5),
    FechSalida DATE,
    FechLlegada DATE,
    FOREIGN KEY(Avion) REFERENCES AVIONES(Matricula) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoO) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoD) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE
);

CREATE TABLE INCIDENTES (
    IdIncidente NUMBER(6) PRIMARY KEY,
    Vuelo NUMBER(6),
    FOREIGN KEY(VUELO) REFERENCES VUELOS(IdVuelo) ON DELETE CASCADE
);

CREATE TABLE DESVIOS (
    IdIncidente NUMBER(6) PRIMARY KEY,
    AeropuertoAlt VARCHAR(5),
    FOREIGN KEY(IdIncidente) REFERENCES INCIDENTES(IdIncidente) ON DELETE CASCADE,
    FOREIGN KEY(AeropuertoAlt) REFERENCES AEROPUERTOS(IATA) ON DELETE CASCADE
);

CREATE TABLE RETRASOS (
    IdIncidente NUMBER(6) PRIMARY KEY,
    Duracion NUMBER(4),
    FOREIGN KEY(IdIncidente) REFERENCES INCIDENTES(IdIncidente) ON DELETE CASCADE
);

CREATE TABLE CAUSAS (
    IdIncidente NUMBER(6),
    Causa VARCHAR(70),
    FOREIGN KEY(IdIncidente) REFERENCES RETRASOS(IdIncidente) ON DELETE CASCADE,
    CONSTRAINT CAUSAS_PK PRIMARY KEY(IdIncidente, Causa)
);



CREATE TABLE CANCELACIONES (
    IdIncidente NUMBER(6) PRIMARY KEY,
    FOREIGN KEY(IdIncidente) REFERENCES INCIDENTES(IdIncidente) ON DELETE CASCADE
);



